
# \u6CE8\u518C\u4E2D\u5FC3\u91C7\u7528\u7A0B\u5E8F\u5458DD\u516C\u76CA\u670D\u52A1\u5668 \u5B98\u65B9\u7F51\u5740 http://blog.didispace.com/ \u611F\u8C22\u63D0\u4F9B
eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

server:
  port: 8000
  tomcat:
    max-threads: 1000
    accept-count: 1000
    max-connections: 2000

spring:
  application:
    name: seckill-producer-8000
  session:
    store-type: none
  redis:
    database: 0
    port: 6379
    password: 117514
    timeout: 3000
    host: 118.190.216.3
  datasource:
      url: jdbc:mysql://118.190.216.3:3306/seckill_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: wustwxl
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location:  classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml